project:
  type: website
  output-dir: docs

website:
  title: "Kênia Barreiro de Souza"
  navbar:
    background: light
    foreground: dark
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: research.qmd
        text: Research

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: article
    grid:
      body-width: 900px
      margin-width: 0px
